server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://49.234.216.89:3306/emptyframe?characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123Wz321Aa!!
  http:
    encoding:
      enabled: false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#和风天气的url和key
weather:
  url: https://free-api.heweather.net/s6/weather/
  key: 615a608b5bd64cc7a00f972a8ae33d05
  #默认查询天津市宁河区的天气
  defaultLocation: ninghe,tianjin
  #now 实况天气，forecast 3天天气预报，hourly逐小时预报，lifestyle生活指数
  weatherType: forecast
  lifestyle: lifestyle