server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://49.234.216.89:3306/emptyframe?characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123Wz321Aa!!
  http:
    encoding:
      enabled: false
shiro:
  #shiro拦截后跳转的登录页
  loginUrl: http://49.234.216.89/login.html
  #shiro登录成功后跳转的首页
  successUrl: http://49.234.216.89/index.html

#和风天气的url和key
weather:
  url: https://free-api.heweather.net/s6/weather/
  key: 615a608b5bd64cc7a00f972a8ae33d05
  #默认查询天津市宁河区的天气
  defaultLocation: ninghe,tianjin
  #now 实况天气，forecast 3天天气预报，hourly逐小时预报，lifestyle生活指数
  weatherType: forecast
  lifestyle: lifestyle