server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://49.234.216.89:3306/emptyframe
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123Wz321Aa!!
